AmeenTraning/AmeenTraning/Models/Purchase_Bill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Bill
    {
        public int Bill_No { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GST_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Transport_Charges { get; set; }
        public Nullable<decimal> Other_Expenses { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<int> Company_Id { get; set; }
    
        public virtual Supplier_Details Supplier_Details { get; set; }
    }
}

AmeenTraning/AmeenTraning/Areas/Inventory/Controllers/Purchase_Bill_Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmeenTraning.Models;

namespace AmeenTraning.Areas.Inventory.Controllers
{
    public class Purchase_Bill_Controller : Controller
    {
        private TrainingEntities db = new TrainingEntities();
        // GET: Inventory/Purchase_Bill_
        public ActionResult Index()
        {
            string Company_Id = string.Empty;
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            var compid = Convert.ToInt32(Company_Id);
            ViewBag.Products = db.Products_Details.Where(e => e.Company_Id == compid).ToList();
            return View();
        }
        public PartialViewResult IndexPartial()
        {
            string Company_Id = string.Empty;
            string UserId = string.Empty;
            string UserName = string.Empty;

            HttpCookie myCookie = Request.Cookies["inventoryCookie"];

            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
            {
                UserId = myCookie.Values["UserId"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
            {
                UserName = myCookie.Values["UserName"].ToString();
            }
            int company_Id = Convert.ToInt32(Company_Id);
            //var PurchaseBills = db.Purchase_Bill.Where(e => e.Company_Id == company_Id).ToList();
            return PartialView(db.Purchase_Bill.ToList());

        }
        public PartialViewResult CreatePartial(int? id)
        {

            string Company_Id = string.Empty;
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            var compid = Convert.ToInt32(Company_Id);
            ViewBag.Date = DateTime.Now.ToString("MM/dd/yyyy");
            ViewBag.Supplier = db.Supplier_Details.Where(e => e.Company_Id == compid).ToList();
            ViewBag.Products = db.Products_Details.Where(e => e.Company_Id == compid).ToList();
            Purchase_Bill bill = new Purchase_Bill();
            if (id != null)
            {
                bill = db.Purchase_Bill.Where(c => c.Bill_No == id).FirstOrDefault();
            }
            return PartialView(bill);
        }

        public int Add(decimal GST, decimal GSTamount, decimal Discount, decimal GrandTotal, int Supplier_ID, decimal Quantity, decimal Transport_Charge, decimal OtherExpences, string Comment, string PaymentMode, decimal Subtotal, int Id)
        {
            string Company_Id = string.Empty;
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            var compid = Convert.ToInt32(Company_Id);

            Purchase_Bill purchase = new Purchase_Bill();
            if (Id != 0)
            {
                purchase = db.Purchase_Bill.Where(e => e.Bill_No == Id).FirstOrDefault();
                purchase.Date_Modified = DateTime.Now;
            }
            else
            {
                purchase.Date_Created = DateTime.Now;
            }
            purchase.Date_Created = DateTime.Now;
            purchase.Company_Id = compid;
            purchase.Supplier_ID = Supplier_ID;
            purchase.Quantity = Quantity;
            purchase.Discount = Discount;
            purchase.GST_Amount = GSTamount;
            purchase.Total_Amount = GrandTotal;
            purchase.Comment = Comment;
            purchase.Transport_Charges = Transport_Charge;
            purchase.Other_Expenses = OtherExpences;
            purchase.Payment_Mode = PaymentMode;
            purchase.GST = GST;
            purchase.SubTotal = Subtotal;
            db.Purchase_Bill.Add(purchase);
            if (Id != 0)
            {
                db.Entry(purchase).State = EntityState.Modified;
            }
            else
            {
                db.Purchase_Bill.Add(purchase);
            }
            db.SaveChanges();
            var Bill_Id = db.Purchase_Bill.Where(e => e.Company_Id == compid && e.Supplier_ID == Supplier_ID && e.Total_Amount == GrandTotal).Select(e => e.Bill_No).FirstOrDefault();

            return Bill_Id;
        }

        public string Add_Item(decimal qty, decimal gst, decimal price, int prodocut_Id, decimal discount, string unit, decimal amount, int bill_No, int? itemid)
        {
            string Company_Id = string.Empty;
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            var compid = Convert.ToInt32(Company_Id);
            Purchase_Bill_Item bill_Item = new Purchase_Bill_Item();
            if (itemid != null)
            {
                bill_Item = db.Purchase_Bill_Item.Where(e => e.Purchase_item_ID == itemid).FirstOrDefault();
                bill_Item.Date_Modified = DateTime.Now;
            }
            else
            {
                bill_Item.Date_Created = DateTime.Now;
            }
            bill_Item.Purchase_Bill_ID = bill_No;
            bill_Item.Product_id = prodocut_Id;
            bill_Item.Quantity = qty;
            bill_Item.Unit = unit;
            bill_Item.Price = price;
            bill_Item.Discount = discount;
            bill_Item.Amount = amount;
            bill_Item.GST = gst;
            db.Purchase_Bill_Item.Add(bill_Item);
            if (itemid != null)
            {
                db.Entry(bill_Item).State = EntityState.Modified;
                db.SaveChanges();
                AddtoStock(Convert.ToInt32(bill_Item.Purchase_Bill_ID), Convert.ToInt32(bill_Item.Product_id), qty, bill_Item.Purchase_item_ID, "update");
            }
            else
            {
                db.Purchase_Bill_Item.Add(bill_Item);
                db.SaveChanges();
                AddtoStock(Convert.ToInt32(bill_Item.Purchase_Bill_ID), Convert.ToInt32(bill_Item.Product_id), qty, bill_Item.Purchase_item_ID,"Add");
            }
            // Stock code


            return "Bill Added";
        }

        public string AddtoStock(int Bill_Id, int Product_Id, decimal qty,int ItemId,string request)
        {
            var stock = db.Stock_Details.Where(e => e.Product_ID == Product_Id).ToList(); 
            decimal tQty = qty;
            if (request == "update")
            {
                if (stock.Count() != 0)
                {
                    var stockq = stock.Where(e => e.Item_ID != ItemId).Select(e => e.Total_Quantity).Sum();
                    if (stockq != 0)
                    {
                        tQty += Convert.ToDecimal(stockq);
                    }
                }
                var stocks = db.Stock_Details.Where(e => e.Item_ID == ItemId).FirstOrDefault();
                stocks.Quantity = qty;
                stocks.Total_Quantity = tQty;
                stocks.Date_Modified = DateTime.Now;
                stocks.Type = "Purchase";
                stocks.Product_ID = Product_Id;
                db.Entry(stocks).State = EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                if (stock.Count() != 0)
                {
                    //var stockq = stock.Where(e => e.Item_ID != ItemId).Select(e => e.Total_Quantity).Sum();
                    var stockq = stock.Where(e => e.Product_ID == Product_Id).ToList();
                    if (stockq.Count() != 0)
                    {
                        tQty += Convert.ToDecimal(stockq);
                    }
                }

                db.Stock_Details.Add(new Stock_Details
                {
                    Quantity = qty,
                    Total_Quantity=tQty,
                    Product_ID=Product_Id,
                    Date_Created=DateTime.Now,
                    Purchase_Bill_ID= Bill_Id,
                    Item_ID=ItemId,
                    Type="Purchase",
                    
                    
                });
                db.SaveChanges();
            }
            return "";
        }
        public ActionResult Delete(int id)
        {
            
            var PurchaseBill_item = db.Purchase_Bill_Item.Where(e => e.Purchase_Bill_ID == id).ToList();
            foreach(var item in PurchaseBill_item)
            {
                var items = db.Purchase_Bill_Item.Where(e => e.Purchase_item_ID == item.Purchase_item_ID).FirstOrDefault();
                db.Purchase_Bill_Item.Remove(items);
                db.SaveChanges();

            }

            Purchase_Bill purchase_Bill = db.Purchase_Bill.Find(id);
            db.Purchase_Bill.Remove(purchase_Bill);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public PartialViewResult Edit(int? id)
		{
            string Company_Id = string.Empty;
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            var compid = Convert.ToInt32(Company_Id);
            var supplier = db.Purchase_Bill.Where(e => e.Bill_No == id).FirstOrDefault();

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Purchase_Bill_/CreatePartial.cshtml
<h4 class="card-title">Purchase Bill</h4>
<div class="col-md-4 float-right mb-3 mt-2">
    <button type="button" class="btn btn-warning" disabled>
        Bill No: 786
    </button>
    <button type="button" class="btn btn-primary" disabled>
        Date: @ViewBag.Date
    </button>
</div>
<div class="row">
    <div class="col-md-8 mb-3 mt-2">

        <div class="input-group">

            <select class="form-control supplier">
                <option selected disabled>Select Supplier</option>
                @foreach (AmeenTraning.Models.Supplier_Details supplier in ViewBag.Supplier)
                {
                    <option id="@supplier.Supplier_Id">@supplier.Name</option>
                }

            </select>
            <div class="input-group-prepend">
                @*<i class="fa fa-user-plus"></i>*@
                <span class="input-group-text btn btn-info ml-1" title="Add New Supplier">+</span>
            </div>
        </div>
    </div>


</div>
<hr>
<div class="row clearfix">
    <div class="col-md-12">
        <table class="table table-bordered table-hover" id="tab_logic">
            <thead>
                <tr>
                    <th class="text-center"> Sr</th>
                    <th class="text-center"> Product </th>
                    <th class="text-center"> Qty </th>
                    <th class="text-center"> Price </th>
                    <th class="text-center"> Unit </th>
                    <th class="text-center"> GST </th>
                    <th class="text-center"> Total </th>
                    <th class="text-center">  </th>
                </tr>
            </thead>
            <tbody class="tody">
                <tr id='addr0'>
                    <td class="col-md-1">1</td>
                    <td class="col-md-5">
                        <select class="form-control" name='product[]'>
                            <option selected disabled>Select Product</option>
                            @foreach (AmeenTraning.Models.Products_Details product in ViewBag.Products)
                            {
                                <option>@product.Name</option>
                            }
                        </select>
                            @*<input type="text" name='product[]' placeholder='' class="form-control" />*@
                    </td>
                    <td class="col-md-1"><input type="number" name='qty[]' placeholder='' class="form-control qty" step="0" min="0" /></td>
                    <td class="col-md-1"><input type="number" name='price[]' placeholder='' class="form-control price" step="0.00" min="0" /></td>
                    <td class="col-md-1"><input type="text" name='unit[]' placeholder='' class="form-control unit" step="0.00" min="0" /></td>
                    <td class="col-md-1"><input type="number" name='gst[]' placeholder='' class="form-control gst" step="0" min="0" /></td>
                    <td class="col-md-1"><input type="number" name='total[]' placeholder='0.00' class="form-control total" readonly /></td>
                    <td class="col-md-1">@*<button id='delete_single_row' class="pull-right btn btn-danger">Delete</button>*@</td>
                </tr>
                @*<tr id='addr1'></tr>*@
            </tbody>
        </table>
    </div>
</div>
<div class="row clearfix">
    <div class="col-md-4">
        <div class="input-group">

            <input type="text" class="form-control" id="adrows" placeholder="Enter Number of rows" required="">
            <div class="input-group-prepend">
                <button id="add_row" class="btn input-group-text btn-success pull-left">Add Row(s)</button>
            </div>
        </div>
       
        @*<button id='delete_row' class="pull-right btn btn-danger">Delete Row</button>*@
    </div>
</div>
<hr>
<div class="row clearfix float-right" style="margin-top:20px">
    <div class="col-lg-2">
        <label for="exampleFormControlTextarea1">Comment:</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="7"></textarea>
    </div>
    <div class="pull-left col-md-4">
        <table class="table table-responsive table-bordered table-hover" id="tab_logic_total">
            <tbody>
                <tr>
                    <th class="text-center">Other Expenses</th>
                    <td class="text-center"><input type="number" name='othexp' placeholder='0.00' class="form-control" id="other_Expenses" /></td>
                </tr>
                <tr>
                    <th class="text-center">Transport Charge</th>
                    <td class="text-center"><input type="number" name='trancharge' placeholder='0.00' class="form-control" id="Transport_Charges" /></td>
                </tr>
               
                <tr>
                    <th class="text-center">Payment</th>
                    <td class="text-center">
                        <div class="d-flex ">
                            <div class="custom-control custom-radio ml-3">
                                <input id="Cash" name="paymentMethod" type="radio" class="custom-control-input" checked="" required="">
                                <label class="custom-control-label" for="credit">Cash</label>
                            </div>
                            <div class="custom-control custom-radio ml-4">
                                <input id="Credit" name="paymentMethod" type="radio" class="custom-control-input" required="">
                                <label class="custom-control-label" for="paypal">Credit</label>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <div class="pull-right col-md-6">
        <table class="table table-bordered table-hover" id="tab_logic_total">
            <tbody>
                <tr>
                    <th class="text-center">Sub Total</th>
                    <td class="text-center"><input type="number" name='sub_total' placeholder='0.00' class="form-control" id="sub_total" readonly /></td>
                </tr>
                <tr>
                    <th class="text-center">GST</th>
                    <td class="text-center">
                        <div class="input-group mb-2 mb-sm-0">
                            <input type="number" class="form-control" id="tax" placeholder="0">
                            <div class="input-group-text">%</div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="text-center">GST Amount</th>
                    <td class="text-center"><input type="number" name='tax_amount' id="tax_amount" placeholder='0.00' class="form-control" readonly /></td>
                </tr>
                <tr>
                    <th class="text-center">Discount</th>
                    <td class="text-center">
                        <div class="input-group mb-2 mb-sm-0">
                            <input type="number" class="form-control" id="disc" placeholder="0">
                            <div class="input-group-text">%</div>
                        </div>
                    </td>

                </tr>
                <tr>
                    <th class="text-center">Grand Total</th>
                    <td class="text-center"><input type="number" name='total_amount' id="total_amount" placeholder='0.00' class="form-control" readonly /></td>
                </tr>
            </tbody>
        </table>
    </div>

</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Purchase_Bill_/Index.cshtml
@{
    ViewBag.Title ="Index";
}

<link href='~/Bootstrap-5/css/mdb.min.css' rel='stylesheet' />

<!------ Include the above in your HEAD tag ---------->
<section>
    <div class='card mt-2'>
        <div class='card-body'>
            <div class='formbill'>
                @Html.Action("IndexPartial", "Purchase_Bill_", new { area = "Inventory" })
            </div>

        </div>
        <hr>
        <section class='btns d-none  text-center mb-3'>
            <a href="/Inventory/Purchase_Bill_/Index"  class='btn btn-warning'>Back to list</a>
            <button class='btnSubmit btn btn-success'>Save</button>
            <button class='btnCancel btn btn-primary'>Save and Print</button>
            <label class='text-danger'></label>
        </section>
    </div>
</section>
<script src='//code.jquery.com/jquery-1.11.1.min.js'></script>
<script src='~/Scripts/jquery-1.10.2.js'></script>
<script>
    $(document).ready(function () {
        var i = 1;
        $(document).on('click', '.btnadd', function () {
          debugger
            $.get('/Inventory/Purchase_Bill_/CreatePartial', function (response) {
                $('.btns').removeClass('d-none');
                $('.formbill').empty();
                $('.formbill').append(response);
            });
        });
        $(document).on('click', '#add_row',function () {
        debugger
            var number = $('#adrows').val();
            var sr = $('#tab_logic >tbody >tr').length;
            for (var a = 1; a <= number; a++) {
                sr++;
                $(".tody").append("<tr><td>" + sr + "</td><td><select class='form-control product' name='product[]'><option selected disabled>Select Product</option>@foreach (AmeenTraning.Models.Products_Details product in ViewBag.Products){<option id='@product.Product_Id'>@product.Name</option>}</select></td><td><input type='number' name='qty[]' placeholder='' class='form-control qty' step='0' min='0'/></td><td><input type='number' name='price[]' placeholder='' class='form-control price' step='0.00' min='0'/></td><td><input type='text' name='unit[]' placeholder='' class='form-control unit' step='0.00' min='0'/></td><td><input type='number' name='gst[]' placeholder='' class='form-control gst' step='0' min='0' /></td><td><input type='number' name='total[]' placeholder='0.00' class='form-control total' readonly/></td><td><button id='delete_single_row' class='pull-right btn btn-danger'>Delete</button></td></td>");
            }

        });
        $(document).on('click', '#delete_single_row', function () {

            //if (i > 1) {
            //    $('#addr' + (i - 1)).html('');
            //    i--;
            //}
            //calc();

            $(this).parent('td').parent('tr').remove();
            calc_total();
        });
     
        $(document).on('keyup change', '#tab_logic tbody', function () {
            calc();
        });
        $('#tax').on('keyup change', function () {
            calc_total();
        });


    });
    $('.delete_single_row').click(function () {

        $(this).parent('tr').empty();

    });

    function calc() {
       debugger
        $('#tab_logic tbody tr').each(function (i, element) {
            var html = $(this).html();
            if (html != '') {
                var qty = $(this).find('.qty').val();
                var gst = $(this).find('.gst').val();
                var price = $(this).find('.price').val();
                var total = qty * price;
                $(this).attr('id', total )
                $(this).find('.total').val((total / 100 * gst) + total);
            }
        });
        calc_total();
    }

    function calc_total()
    {
        debugger
        total = 0;
        $('.total').each(function () {
            total += parseInt($(this).val());
        });
        var price = 0;
        $('#tab_logic tbody tr').each(function () {
            price += parseInt($(this).attr('id'));
        });
        eachgst()
        $('#sub_total').val(price.toFixed(2));
        var subtotal = parseInt($('#sub_total').val());
        tax_sum = subtotal / 100 * $('#tax').val();
        $('#tax_amount').val(tax_sum.toFixed(2));
        $('#total_amount').val(subtotal + tax_sum);
        var other_Expense = parseInt($('#other_Expenses').val());
        var Transcharges = parseInt($('#Transport_Charges').val());
        var sum = 0;
        
    }

    function eachgst()
    {
       debugger
        var grnTotal = 0;
        $(".gst").each(function () {
            var gst = parseFloat($(this).val());
            grnTotal += isNaN(gst) ? 0 : gst;
        });
        $('#tax').val(grnTotal.toFixed(2));
    }

   // Other expenses and transport charges
    $(document).on("keyup change", "#Transport_Charges", function () {
        debugger
        OtherCharge()
    });
    $(document).on("keyup change", "#other_Expenses", function () {
        debugger
        OtherCharge()
    });
    function OtherCharge()
    {
        debugger;
        calc_total();
        var grant_total = parseInt($('#total_amount').val());
        var other_Expense = parseInt($('#other_Expenses').val());
        var Transcharges = parseInt($('#Transport_Charges').val());
        var sum = 0;
        if ($.isNumeric(other_Expense) && $.isNumeric(Transcharges)) {
            sum = parseInt(grant_total + other_Expense + Transcharges);
            $('#total_amount').val(sum);
        }
        else if ($.isNumeric(other_Expense)) {
            sum = parseInt(grant_total + other_Expense);
            $('#total_amount').val(sum);
        }
        else if ($.isNumeric(Transcharges)) {
            sum = parseInt(grant_total + Transcharges);
            $('#total_amount').val(sum);
        }
        else {
            calc_total();
        }
    }

    // Discount
    $(document).on("keyup change", "#disc", function () {
        discount()
    });
    function discount()
    {
        debugger
        calc_total();
        debugger
        OtherCharge()
        var grant_total = parseInt($('#total_amount').val());
        var disc = parseInt($('#disc').val());
        var discounted_price;
        if ($.isNumeric(grant_total) && $.isNumeric(disc)) {
            discounted_price = parseInt(grant_total - (grant_total * disc / 100));
            $('#total_amount').val(discounted_price);
        }
        else {
            calc_total();
            OtherCharge()
        }
    }
    var Id = 0;
    //Subit Function
    $(document).on('click','.btnSubmit', function () {
        debugger
        var Subtotal = $('#sub_total').val();
        var GST = $('#tax').val();
        var GSTamount = $('#tax_amount').val();
        var Discount = $('#disc').val();
        var GrandTotal = $('#total_amount').val();
        var Supplier_ID = $(".supplier option:selected").attr('id');
        var Quantity = $('#tab_logic >tbody >tr').length;
        var Transport_Charge = $('#Transport_Charges').val();
        var OtherExpences = $('#other_Expenses').val();
        var Comment = $('#exampleFormControlTextarea1').val();
        var PaymentMode = $("input[name='paymentMethod']:checked").val();
        
        $.post('/Inventory/Purchase_Bill_/Add', { GST, GSTamount, Discount, GrandTotal, Supplier_ID, Quantity, Transport_Charge, OtherExpences, Comment, PaymentMode, Subtotal, Id},
            function (data, status) {
                
                if (data != 0)
                {
                    Id = 0;
                    $('#tab_logic tbody tr').each(function (i, element) {
                        debugger
                        var qty = $(this).find('.qty').val();
                        var gst = $(this).find('.gst').val();
                        var price = $(this).find('.price').val();
                        var prodocut_Id = $(".product option:selected").attr('id');
                        var discount = $('#disc').val();
                        var unit = $(this).find('.unit').val();
                        var amount = $(this).find('.total').val();
                        var bill_No = data;
                        var itemid = $(this).find('.itemid').attr('id');
                        $.post('/Inventory/Purchase_Bill_/Add_Item', { qty, gst, price, prodocut_Id, discount, unit, amount, bill_No, itemid},
                            function (data, status) {
                              
                            });

                    });

                
                    LoadProjects();
                    Swal.fire(
                        'Suceed!',
                        data,
                        'success'
                    )
                }
            });
    });
    function LoadProjects() {
        $.get('/Inventory/Purchase_Bill_/IndexPartial', function (response) {
            $('.formbill').empty();
            $('.formbill').append(response);
            $('.btns').addClass('d-none');
        });
    }


    // delete
    $(document).on('click', '.btndelete', function () {
        var id = $(this).attr('Id');
        Id = id;
        Swal.fire({
            title: 'Are you sure?',
            text: 'You will not be able to recover this Unit & related data will also!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.value) {
                $.get('/Inventory/Purchase_Bill_/Delete?id=' + id, function (response) {
                    LoadProjects();
                    Id = 0;
                })
            } else {
                Swal.fire(
                    'Cancelled',
                    'Unit is active :)',
                    'error'
                )
            }
        });
    });

    $(document).on('click', '.btnEdit', function () {
        debugger
        var id = $(this).attr('Id');
        Id = id;
        $.get('/Inventory/Purchase_Bill_/Edit?id=' + id, function (response) {
            $('.formbill').empty();
            $('.formbill').append(response);
            $('.btns').removeClass('d-none');
        });
    })

</script>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Purchase_Bill_/IndexPartial.cshtml
@model IEnumerable<AmeenTraning.Models.Purchase_Bill>

@{

    var Sr = 0;
}
<table class="table">
    <thead>
        <tr>
            <th>SR</th>
            <th>
                Bill No
            </th>
            <th>
                Supplier Name
            </th>
            <th>
                Total Amount
            </th>
            <th>
                Quantity
            </th>
            <th>
                GST Amount
            </th>
            <th>
                Date Created
            </th>
            <th>
                Payment Mode
            </th>

            <th>
                <div>
                    <button type="button" class="btn btn-primary btnadd">
                        Add
                    </button>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            Sr++;
        <tr>
            <td>@Sr</td>
            <td>
                @Html.DisplayFor(modelItem => item.Bill_No)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier_Details.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total_Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GST_Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Payment_Mode)
            </td>

            <td>
                <button Id="@item.Bill_No" class="btn btnEdit btn-warning">Edit</button>
                <button Id="@item.Bill_No" class="btn btndelete btn-danger">Delete</button>
            </td>
        </tr>
        }

    </tbody>
</table>