AmeenTraning/AmeenTraning/Models/Supplier_Details.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Details()
        {
            this.Purchase_Bill = new HashSet<Purchase_Bill>();
        }
    
        public int Supplier_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Mobile1 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Company_Details Company_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Bill> Purchase_Bill { get; set; }
    }
}

AmeenTraning/AmeenTraning/Areas/Inventory/Controllers/Supplier_DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmeenTraning.Models;

namespace AmeenTraning.Areas.Inventory.Controllers
{
    public class Supplier_DetailsController : Controller
    {
        private TrainingEntities db = new TrainingEntities();

        // GET: Inventory/Supplier_Details
        public ActionResult Index()
        {

            string Company_Id = string.Empty;

            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (myCookie == null)
            {
                return Redirect("/Auth/Login/Logout");
            }
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            var supplier_Details = db.Supplier_Details.Include(s => s.Company_Details);
            return View();
        }

        // Partial View
        public PartialViewResult IndexPartial()
        {
            string Company_Id = string.Empty;
            string UserId = string.Empty;
            string UserName = string.Empty;

            HttpCookie myCookie = Request.Cookies["inventoryCookie"];

            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
            {
                UserId = myCookie.Values["UserId"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
            {
                UserName = myCookie.Values["UserName"].ToString();
            }
            int company_Id = Convert.ToInt32(Company_Id);
            //var products_Details = db.Products_Details.Include(p => p.Category_Details).Include(p => p.Company_Details);
            return PartialView(db.Supplier_Details.ToList());
        }
        // GET: Inventory/Supplier_Details/Details/5

        public PartialViewResult CreatePartial(int? id)
        {
            string Company_Id = string.Empty;

            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            Supplier_Details car = new Supplier_Details();
            if (id != null)
            {
                car = db.Supplier_Details.Where(c => c.Supplier_Id == id).FirstOrDefault();
            }
            return PartialView(car);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier_Details supplier_Details = db.Supplier_Details.Find(id);
            if (supplier_Details == null)
            {
                return HttpNotFound();
            }
            return View(supplier_Details);
        }

        // GET: Inventory/Supplier_Details/Create
        public ActionResult Create()
        {
            ViewBag.Company_Id = new SelectList(db.Company_Details, "Company_Id", "Name");
            return View();
        }

        // POST: Inventory/Supplier_Details/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Supplier_Id,Company_Id,Name,Email,Mobile,Mobile1,Address,City,State,Country,Created_By,Modified_By,Date_Created,Date_Modified")] Supplier_Details supplier_Details)
        {
            if (ModelState.IsValid)
            {
                db.Supplier_Details.Add(supplier_Details);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Company_Id = new SelectList(db.Company_Details, "Company_Id", "Name", supplier_Details.Company_Id);
            return View(supplier_Details);
        }

        // Add function 
        public string Add(string name, string email, string mobile, string address,int Id)
        {
            string Returns = "";
            if (ModelState.IsValid)
            {
                string Company_Id = string.Empty;
                string UserId = string.Empty;
                string UserName = string.Empty;

                HttpCookie myCookie = Request.Cookies["inventoryCookie"];
                if (myCookie == null)
                {
                    return "Logout";
                }
                if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
                {
                    Company_Id = myCookie.Values["Company_Id"].ToString();
                }
                if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
                {
                    UserId = myCookie.Values["UserId"].ToString();
                }
                if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
                {
                    UserName = myCookie.Values["UserName"].ToString();
                }
                int company_Id = Convert.ToInt32(Company_Id);
                if (Id != 0)
                {
                    Supplier_Details supplier = db.Supplier_Details.Where(e => e.Supplier_Id == Id).FirstOrDefault();
                    supplier.Company_Id = company_Id;
                    supplier.Created_By = UserName;
                    supplier.Date_Created = DateTime.Now;
                    supplier.Name = name;
                    supplier.Email = email;
                    supplier.Date_Modified = DateTime.Now;
                    supplier.Mobile = mobile;
                    supplier.Address = address;
                    db.Entry(supplier).State = EntityState.Modified;
                    db.SaveChanges();
                    return "Supplier Updated Successfully";
                }
                else
                {
                    Supplier_Details supplier = db.Supplier_Details.Where(e => e.Name == name && e.Company_Id == company_Id).FirstOrDefault();
                    if (supplier == null)
                    {
                        Supplier_Details supplier_Details = new Supplier_Details();
                        supplier_Details.Company_Id = company_Id;
                        supplier_Details.Created_By = UserName;
                        supplier_Details.Date_Created = DateTime.Now;
                        supplier_Details.Name = name;
                        supplier_Details.Email = email;
                        supplier_Details.Mobile = mobile;
                        supplier_Details.Address = address;
                        db.Supplier_Details.Add(supplier_Details);
                        db.SaveChanges();
                        return "Supplier Added Successfully";
                    }
                    else
                    {
                        return "Supplier Already Exist";
                    }

                }

               
            }
            return Returns;
        }
        // GET: Inventory/Supplier_Details/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier_Details supplier_Details = db.Supplier_Details.Find(id);
            if (supplier_Details == null)
            {
                return HttpNotFound();
            }
            ViewBag.Company_Id = new SelectList(db.Company_Details, "Company_Id", "Name", supplier_Details.Company_Id);
            return View(supplier_Details);
        }

        // POST: Inventory/Supplier_Details/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Supplier_Id,Company_Id,Name,Email,Mobile,Mobile1,Address,City,State,Country,Created_By,Modified_By,Date_Created,Date_Modified")] Supplier_Details supplier_Details)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplier_Details).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Company_Id = new SelectList(db.Company_Details, "Company_Id", "Name", supplier_Details.Company_Id);
            return View(supplier_Details);
        }

        // GET: Inventory/Supplier_Details/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier_Details supplier_Details = db.Supplier_Details.Find(id);
            if (supplier_Details == null)
            {
                return HttpNotFound();
            }
            return View(supplier_Details);
        }

        // POST: Inventory/Supplier_Details/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier_Details supplier_Details = db.Supplier_Details.Find(id);
            db.Supplier_Details.Remove(supplier_Details);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Supplier_Details/Create.cshtml
@model AmeenTraning.Models.Supplier_Details

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Supplier_Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Company_Id, "Company_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Company_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Company_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created_By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created_By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created_By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modified_By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modified_By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modified_By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Modified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Modified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Modified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Supplier_Details/CreatePartial.cshtml
@model AmeenTraning.Models.Supplier_Details
@{
    ViewBag.Title = "Create";
}
    <section>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal border p-5">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
         
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
                }
        </section>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Supplier_Details/Delete.cshtml
@model AmeenTraning.Models.Supplier_Details

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Supplier_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Details.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Details.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Supplier_Details/Details.cshtml
@model AmeenTraning.Models.Supplier_Details

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Supplier_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Details.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Details.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Supplier_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Supplier_Details/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<section>
    <div class="card mt-2">
        <div class="card-body">
            <h5 class="card-title">Supplier</h5>

            
            <div class="formtabl">
                @Html.Action("IndexPartial", "Supplier_Details", new { area = "Inventory" })
            </div>
            <section class="btns d-none">
                <button class="btnSubmit btn btn-primary">Save</button>
                <button class="btnCancel btn btn-danger">Cancel</button>
                <label class="text-danger"></label>
            </section>
          

        </div>
    </div>
</section>


<script src="~/Scripts/jquery-1.10.2.js"></script>

<script>
    var Id = 0;
    $(document).on('click', '.btnadd', function () {
        debugger
        $.get('/Inventory/Supplier_Details/CreatePartial', function (response) {
            $('.btns').removeClass('d-none');
            $('.formtabl').empty();
            $('.formtabl').append(response);
        });
    });
    $(document).on('click', '.btnSubmit', function () {
        $('tbody').empty();
        var name = $('input[name="Name"]').val();
        var email = $('input[name="Email"]').val();
        var mobile = $('input[name="Mobile"]').val();
        var address = $('input[name="Address"]').val();

        $('label.text-danger').empty();
        if (name == "") {
            $('label.text-danger').append('Please Enter Your Name');
            return false;
        }
        if (email == "") {
            $('label.text-danger').append('Please Enter Your Email');
            return false;
        }
        if (mobile == "") {
            $('label.text-danger').append('Please Enter Your Mobile NO');
            return false;
        }
        if (address == "") {
            $('label.text-danger').append('Please Enter Your Address');
            return false;
        }

        $.post('/Inventory/Supplier_Details/Add', { name, email, mobile, address, Id},
            function (data, status) {
                    Swal.fire(
                        'Suceed!',
                        data,
                        'success'
                    )
                LoadProjects();
                Id = 0;
                $('input[name="Name"]').val('');
                $('input[name="Email"]').val('');
                $('input[name="Mobile"]').val('');
                $('input[name="Address"]').val('');
                $('#basicExampleModal').modal('toggle');
            });
        
    });
    function LoadProjects() {
        $.get('/Inventory/Supplier_Details/IndexPartial', function (response) {
            $('.formtabl').empty();
            $('.formtabl').append(response);
            $('.btns').addClass('d-none');
        });
    }
    $(document).on('click', '.btnEdit', function () {
        debugger
        var id = $(this).attr('Id');
        Id = id;
        $.get('/Inventory/Supplier_Details/CreatePartial?id=' + id, function (response) {
            $('.btns').removeClass('d-none');
            $('.formtabl').empty();
            $('.formtabl').append(response);
        });
    })
    $(document).on('click', '.btnCancel', function () {
        $.get('/Inventory/Supplier_Details/IndexPartial', function (response) {
            $('.formtabl').empty();
            $('.formtabl').append(response);
            $('.btns').addClass('d-none');
            Id = 0;
        });
    })
    $(document).on('click', '.btndelete', function () {
        var id = $(this).attr('Id');
        Id = id;
        Swal.fire({
            title: 'Are you sure?',
            text: 'You will not be able to recover this supplier & related data will also!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.value) {
                $.get('/Inventory/Supplier_Details/Delete?id=' + id, function (response) {
                    LoadProjects();
                    Id = 0;
                })
            } else {
                Swal.fire(
                    'Cancelled',
                    'Unit is active :)',
                    'error'
                )
            }
        });
    });
</script>