AmeenTraning/AmeenTraning/Models/Products_Details.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_Details()
        {
            this.Purchase_Bill_Item = new HashSet<Purchase_Bill_Item>();
            this.Sales_Bill_item = new HashSet<Sales_Bill_item>();
        }
    
        public int Product_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
    
        public virtual Category_Details Category_Details { get; set; }
        public virtual Company_Details Company_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Bill_Item> Purchase_Bill_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Bill_item> Sales_Bill_item { get; set; }
    }
}

AmeenTraning/AmeenTraning/Areas/Inventory/Controllers/Products_DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmeenTraning.Models;

namespace AmeenTraning.Areas.Inventory.Controllers
{
    public class Products_DetailsController : Controller
    {
        private TrainingEntities db = new TrainingEntities();

        // GET: Inventory/Products_Details
        public ActionResult Index()
        {
            string Company_Id = string.Empty;
            
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (myCookie == null)
            {
                return Redirect("/Auth/Login/Logout");
            }
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            int company_Id = Convert.ToInt32(Company_Id);
        

            return View();
           
        }

        public PartialViewResult IndexPartial()
        {
            string Company_Id = string.Empty;
            string UserId = string.Empty;
            string UserName = string.Empty;

            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
          
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
            {
                UserId = myCookie.Values["UserId"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
            {
                UserName = myCookie.Values["UserName"].ToString();
            }
            int company_Id = Convert.ToInt32(Company_Id);
            var products_Details = db.Products_Details.Include(p => p.Category_Details).Include(p => p.Company_Details);
            return PartialView(products_Details.ToList());
        }

        public PartialViewResult CreatePartial(int ? id)
        {
            string Company_Id = string.Empty;

            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
           
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            int company_Id = Convert.ToInt32(Company_Id);
            ViewBag.Category = db.Category_Details.Where(e => e.Company_Id == company_Id).ToList();
            if (id != null)
            {
                var prod = db.Products_Details.Find(id);
                ViewBag.Category_Id = prod.Category_Id;
                ViewBag.Name = prod.Name;
                ViewBag.Description = prod.Description;
            }
            return PartialView();
        }
        public string Add(string category, string name, string Description,int Id)
        {
            string Returns = "";
            if (ModelState.IsValid)
            {
                string Company_Id = string.Empty;
                string UserId = string.Empty;
                string UserName = string.Empty;

                HttpCookie myCookie = Request.Cookies["inventoryCookie"];
                if (myCookie == null)
                {
                    return "Logout";
                }
                if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
                {
                    Company_Id = myCookie.Values["Company_Id"].ToString();
                }
                if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
                {
                    UserId = myCookie.Values["UserId"].ToString();
                }
                if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
                {
                    UserName = myCookie.Values["UserName"].ToString();
                }
                int company_Id = Convert.ToInt32(Company_Id);
                if (Id != 0)
                {
                    Products_Details prds = db.Products_Details.Find(Id);
                    prds.Category_Id = Convert.ToInt32(category);
                    prds.Modified_By = UserName;
                    prds.Date_Modified = DateTime.Now;
                    prds.Description = Description;
                    prds.Name = name;
                    db.Entry(prds).State = EntityState.Modified;
                    db.SaveChanges();
                    return "Product Upadated Successfully";
                }
                Products_Details prd = db.Products_Details.Where(e => e.Company_Id == company_Id && e.Name == name).FirstOrDefault();

                if (prd == null)
                { 
                   Products_Details products_Details = new Products_Details();    
                   products_Details.Company_Id = company_Id;
                   products_Details.Category_Id = Convert.ToInt32(category);
                   products_Details.Created_By = UserName;
                   products_Details.Date_Created = DateTime.Now;
                   products_Details.Description = Description;
                   products_Details.Name = name;
                   db.Products_Details.Add(products_Details);
                   db.SaveChanges();
                   return "Product Added Successfully";
                } else
                {
                   return "Product Already Exist";
                }           
            }
            return Returns;
        }
       
        public ActionResult Delete(int id)
        {
            Products_Details products_Details = db.Products_Details.Find(id);
            db.Products_Details.Remove(products_Details);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Products_Details/Create.cshtml
@model AmeenTraning.Models.Products_Details

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Products_Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Company_Id, "Company_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Company_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Company_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, "Category_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created_By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created_By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created_By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modified_By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modified_By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modified_By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Modified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Modified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Modified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Products_Details/CreatePartial.cshtml
@{
    
}

<div class="form-outline mb-4">
    <select name="ddlCategory" class="form-control" id="form1Example1">
        @foreach (AmeenTraning.Models.Category_Details item in ViewBag.Category)
        {
            if (ViewBag.Category_Id != null)
            {
                if (ViewBag.Category_Id == item.Category_Id)
                {
                    <option value="@item.Category_Id" selected>@item.Name</option>
                }
                else
                {
                    <option value="@item.Category_Id">@item.Name</option>
                }
            }
            else
            {
                <option value="@item.Category_Id">@item.Name</option>

            }

        }
    </select>
    <label class="form-label" for="form1Example1">Category</label>
</div>

<div class="form-outline mb-4">
    <input type="text" id="form1Example13" name="Name" value="@ViewBag.Name" class="form-control mb-4">
    <label class="form-label" for="form1Example3">Name</label>
</div>

<div class="form-outline mb-4">
    <input id="form1Example12" name="Description" value="@ViewBag.Description" class="form-control mb-4">
    <label class="form-label" for="form1Example2">Description</label>
</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Products_Details/Delete.cshtml
@model AmeenTraning.Models.Products_Details

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Products_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Details.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Details.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Details.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Details.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Products_Details/Details.cshtml
@model AmeenTraning.Models.Products_Details

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Products_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Details.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Details.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Details.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Details.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Product_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Products_Details/Edit.cshtml
@model AmeenTraning.Models.Products_Details

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Products_Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Product_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Company_Id, "Company_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Company_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Company_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, "Category_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Category_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created_By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created_By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created_By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modified_By, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modified_By, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modified_By, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Modified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Modified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Modified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Products_Details/Index.cshtml
@{
    ViewBag.Title = "Index";
   
}

<section>
    <div class="card mt-2">
        <div class="card-body">
            <h5 class="card-title">Customers</h5>

            <div class="formtabl">
                @Html.Action("IndexPartial", "Products_Details", new { area = "Inventory" })
            </div>
            <section class="btns d-none">
                <button class="btnSubmit btn btn-primary">Save</button>
                <button class="btnCancel btn btn-danger">Cancel</button>
                <label class="text-danger"></label>
            </section>
        </div>
        </div>
</section>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    var Id = 0;
    $(document).on('click', '.btnadd', function () {
        $.get('/Inventory/Products_Details/CreatePartial', function (response) {
            $('.btns').removeClass('d-none');
            $('.formtabl').empty();
            $('.formtabl').append(response);
        });
    });
    $(document).on('click', '.btnSubmit', function () {

        var category = $('select[name="ddlCategory"]').val();
        var name = $('input[name="Name"]').val();
        var Description = $('input[name="Description"]').val();

        $('label.text-danger').empty();
        if (name == "") {
            $('label.text-danger').append('Please Enter Your Name');
            return false;
        }
        if (Description == "") {
            $('label.text-danger').append('Please Enter Description');
            return false;
        }
        $.post('/Inventory/Products_Details/Add', { category, name, Description, Id },
            function (data, status) {
                Swal.fire(
                    'Suceed!',
                    data,
                    'success'
                )
                LoadProjects();
                Id = 0;
                $('input[name="Name"]').val('');
                $('input[name="Description"]').val('');
                $('#basicExampleModal').modal('toggle');
            });

    });
    $(document).on('click', '.btnEdit', function () {
        debugger
        var id = $(this).attr('Id');
        Id = id;
        $.get('/Inventory/Products_Details/CreatePartial?id=' + id, function (response) {
            $('.btns').removeClass('d-none');
            $('.formtabl').empty();
            $('.formtabl').append(response);
        });
    })
    $(document).on('click', '.btnCancel', function () {
        $.get('/Inventory/Products_Details/IndexPartial', function (response) {
            $('.formtabl').empty();
            $('.formtabl').append(response);
            $('.btns').addClass('d-none');
            Id = 0;
        });
    })
    function LoadProjects() {
        $.get('/Inventory/Products_Details/IndexPartial', function (response) {
            $('.formtabl').empty();
            $('.formtabl').append(response);
        });
    }
    $(document).on('click', '.btndelete', function () {
        var id = $(this).attr('Id');
        Id = id;
        Swal.fire({
            title: 'Are you sure?',
            text: 'You will not be able to recover this Unit & related data will also!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.value) {
                $.get('/Inventory/Products_Details/Delete?id=' + id, function (response) {
                    LoadProjects();
                    Id = 0;
                })
            } else {
                Swal.fire(
                    'Cancelled',
                    'Unit is active :)',
                    'error'
                )
            }
        });
    });
</script>

































@*@foreach (var item in Model)
            {
                Sr++;
            <tr>
                <td class="text-center">@Sr</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category_Details.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created_By)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modified_By)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Modified)
                </td>

                @*<td>
        @Html.DisplayFor(modelItem => item.Company_Details.Name)
    </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Product_Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Product_Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Product_Id })
                </td>
                <td>
                    <a href="/Inventory/Products_Details/Edit?id=@item.Product_Id" class="btn btn-info">Edit</a> |
                    <a href="/Inventory/Products_Details/Delete?id=@item.Product_Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            }*@












@*<tr>
        <th>Sr</th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created_By)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modified_By)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Modified)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category_Details.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company_Details.Name)
        </th>
        <th></th>
    </tr>*@

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Products_Details/IndexPartial.cshtml
@model IEnumerable<AmeenTraning.Models.Products_Details>

@{
    
    var Sr = 0;
}
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Sr</th>
            <th>
                Category
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Createad By
            </th>
            <th>
                Modified By
            </th>
            <th>
                Date Created
            </th>
            <th>
                Date Modified
            </th>
            @*<th> <a href="/Inventory/Products_Details/Create" class="btn btn-info"> Add </a></th>*@

            <th>
                <div>
                    <button type="button"
                            class="btn btn-primary btnadd">
                        Add
                    </button>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            Sr++;
            <tr>
                <td>@Sr</td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category_Details.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created_By)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modified_By)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Modified)
                </td>

                <td>
                    <button type="button" Id="@item.Product_Id"
                            class="btn btn-warning btn-sm btnEdit">
                        Edit
                    </button>
                    <button type="button" Id="@item.Product_Id"
                            class="btn btn-danger btn-sm btndelete">
                        Delete
                    </button>
                </td>
            </tr>
        }

    </tbody>
</table>