AmeenTraning/AmeenTraning/Models/Units_Details.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmeenTraning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units_Details
    {
        public int Unit_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Modified { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Company_Details Company_Details { get; set; }
    }
}

AmeenTraning/AmeenTraning/Areas/Inventory/Controllers/Units_DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AmeenTraning.Models;

namespace AmeenTraning.Areas.Inventory.Controllers
{
    public class Units_DetailsController : Controller
    {
        private TrainingEntities db = new TrainingEntities();

        // GET: Inventory/Units_Details
        public ActionResult Index()
        {
            string Company_Id = string.Empty;
          
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (myCookie == null)
            {
                return Redirect("/Auth/Login/Logout");
            }
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
           

            int company_Id = Convert.ToInt32(Company_Id);
            ViewBag.Units = db.Units_Details.Where(e => e.Company_Id == company_Id).ToList();
            return View();
        }

        public PartialViewResult IndexPartial()
        {
            string Company_Id = string.Empty;
            string UserId = string.Empty;
            string UserName = string.Empty;

            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
            {
                UserId = myCookie.Values["UserId"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
            {
                UserName = myCookie.Values["UserName"].ToString();
            }

            int company_Id = Convert.ToInt32(Company_Id);
            return PartialView(db.Units_Details.ToList());
        }
        // GET: Inventory/Units_Details/Details/5
        public PartialViewResult CreatePartial(int ? id)
        {
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            string Company_Id = string.Empty;
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            Units_Details car = new Units_Details();
            if (id != null)
            {
                car = db.Units_Details.Where(c => c.Unit_Id == id).FirstOrDefault();
            }
            return PartialView(car);
        }
            public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Units_Details units_Details = db.Units_Details.Find(id);
            if (units_Details == null)
            {
                return HttpNotFound();
            }
            return View(units_Details);
        }


        // GET: Inventory/Units_Details/Create
        public ActionResult Create()
        {
            ViewBag.Company_Id = new SelectList(db.Company_Details, "Company_Id", "Name");
            return View();
        }

        // POST: Inventory/Units_Details/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(Units_Details units_Details)
        {
            if (ModelState.IsValid)
            {
            string Company_Id = string.Empty;
            string UserId = string.Empty;
            string UserName = string.Empty;
            HttpCookie myCookie = Request.Cookies["inventoryCookie"];
            if (myCookie == null)
            {
                return Redirect("/Auth/Login/Logout");
            }
            if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
            {
                Company_Id = myCookie.Values["Company_Id"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
            {
                UserId = myCookie.Values["UserId"].ToString();
            }
            if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
            {
                UserName = myCookie.Values["UserName"].ToString();
            }

            Units_Details cart = new Units_Details();
            cart.Created_By = UserName;
            cart.Date_Created = DateTime.Now;
            cart.Company_Id = Convert.ToInt32(Company_Id);
            cart.Name = units_Details.Name;
            db.Units_Details.Add(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
           
                //db.units_details.add(units_details);
                //db.savechanges();
                //return redirecttoaction("index");
            }
    //        ViewBag.Company_Id = new SelectList(db.Company_Details, "Company_Id", "Name", units_Details.Company_Id);
            return View(units_Details);
        }

        public string Add(string name, int Id)
        {
            string Returns = "";
            if (ModelState.IsValid)
            {
                string Company_Id = string.Empty;
                string UserId = string.Empty;
                string UserName = string.Empty;

                HttpCookie myCookie = Request.Cookies["inventoryCookie"];
                if (myCookie == null)
                {
                    return "Logout";
                }
                if (!string.IsNullOrEmpty(myCookie.Values["Company_Id"]))
                {
                    Company_Id = myCookie.Values["Company_Id"].ToString();
                }
                if (!string.IsNullOrEmpty(myCookie.Values["UserId"]))
                {
                    UserId = myCookie.Values["UserId"].ToString();
                }
                if (!string.IsNullOrEmpty(myCookie.Values["UserName"]))
                {
                    UserName = myCookie.Values["UserName"].ToString();
                }
                int company_Id = Convert.ToInt32(Company_Id);
             
               
                if (Id != 0)
                {
                    Units_Details units = db.Units_Details.Where(e => e.Unit_Id == Id).FirstOrDefault();
                    units.Company_Id = company_Id;
                    units.Created_By = UserName;
                    units.Date_Created = DateTime.Now;
                    units.Name = name;
                    db.Entry(units).State = EntityState.Modified;
                    db.SaveChanges();
                    return "Unit Updated Successfully";
                }
               else
                {
                    Units_Details units = db.Units_Details.Where(e => e.Name == name && e.Company_Id == company_Id).FirstOrDefault();
                    if (units == null)
                    {
                        Units_Details units_Details = new Units_Details();
                        units_Details.Company_Id = company_Id;
                        units_Details.Created_By = UserName;
                        units_Details.Date_Created = DateTime.Now;
                        units_Details.Date_Modified = DateTime.Now;
                        units_Details.Name = name;
                        db.Units_Details.Add(units_Details);
                        db.SaveChanges();
                        return "Unit Added Successfully";
                    }
                    else
                    {
                        return "Unit Already Exist";
                    }

                }
                
            }
            return Returns;
        }
        // GET: Inventory/Units_Details/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Units_Details units_Details = db.Units_Details.Find(id);
            if (units_Details == null)
            {
                return HttpNotFound();
            }
            return View(units_Details);
        }

        // POST: Inventory/Units_Details/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Unit_Id,Company_Id,Name,Date_Created,Date_Modified,Created_By,Modified_By")] Units_Details units_Details)
        {
            if (ModelState.IsValid)
            {
                db.Entry(units_Details).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(units_Details);
        }

    
        public ActionResult Delete(int id)
        {
            Units_Details units_Details = db.Units_Details.Find(id);
            db.Units_Details.Remove(units_Details);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Units_Details/Create.cshtml
@model AmeenTraning.Models.Units_Details

@{
    ViewBag.Title = "Create";
}

<section>
    <div class="card mt-2">
        <div class="card-body">
            <h5 class="card-title">Add Unit</h5>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal border p-5">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-outline">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control mb-4", id = "Name" } })
                        <label class="form-label" for="Name">Name</label>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-success" />
                            <a href="/Inventory/Units_Details" class="btn btn-warning">Back to List</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Units_Details/CreatePartial.cshtml
@model AmeenTraning.Models.Units_Details
@{
    ViewBag.Title = "Create";
}
<section>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal border p-5">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-outline">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control mb-4", id = "Name" } })
                <label class="form-label" for="Name">Unit</label>
            </div>
        </div>
    }
</section>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Units_Details/Delete.cshtml
@model AmeenTraning.Models.Units_Details

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Units_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Company_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified_By)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Units_Details/Details.cshtml
@model AmeenTraning.Models.Units_Details

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Units_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Company_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_By)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified_By)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified_By)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Unit_Id }) |
    <a href="/Employees/Index" class="btn btn-warning">Back to List</a>
</p>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Units_Details/Edit.cshtml
@model AmeenTraning.Models.Units_Details

@{
    ViewBag.Title = "Edit";
}

<section>
    <div class="card mt-2">
        <div class="card-body">
            <h4 class="card-title">Edit Units</h4>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()


            <div class="form-horizontal border p-3">
                @*<hr />*@
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Unit_Id)
                <div class="form-outline">
                    @*@Html.LabelFor(model => model.Company_Id, htmlAttributes: new { @class = "col-sm-2 control-label col-md-2" })*@

                    @Html.EditorFor(model => model.Company_Id, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.Company_Id, "", new { @class = "text-danger" })
                    <label class="form-label" for="Company_Id">Company Id</label>

                </div>
                <div class="form-outline">
                    @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@

                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    <label class="form-label" for="Name">Name</label>

                </div>
                <div class="form-outline">
                    @*@Html.LabelFor(model => model.Date_Created, htmlAttributes: new { @class = "control-label col-md-2" })*@

                    @Html.EditorFor(model => model.Date_Created, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.Date_Created, "", new { @class = "text-danger" })
                    <label class="form-label" for="Date_Created">Date Created</label>

                </div>
                <div class="form-outline">
                    @*@Html.LabelFor(model => model.Date_Modified, htmlAttributes: new { @class = "control-label col-md-2" })*@

                    @Html.EditorFor(model => model.Date_Modified, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.Date_Modified, "", new { @class = "text-danger" })
                    <label class="form-label" for="Date_Modified">Date Modified</label>

                </div>
                <div class="form-outline">
                    @*@Html.LabelFor(model => model.Created_By, htmlAttributes: new { @class = "control-label col-md-2" })*@

                    @Html.EditorFor(model => model.Created_By, new { htmlAttributes = new { @class = "form-control mb-4" } })
                    @Html.ValidationMessageFor(model => model.Created_By, "", new { @class = "text-danger" })
                    <label class="form-label" for="Created_By">Created By</label>

                </div>
                <div class="form-outline">

                    @Html.EditorFor(model => model.Modified_By, new { htmlAttributes = new { @class = "form-control mb-4", id = "Name" } })
                    @Html.ValidationMessageFor(model => model.Modified_By, "", new { @class = "text-danger" })
                    <label class="form-label" for="Modified_By">Modified By</label>

                </div>
                <div class="form-group p-1">
                    <div class="col-md-offset-2 col-md-10 ">
                        <input type="submit" value="Update" class="btn btn-info" />
                        <a href="/Inventory/Units_Details" class="btn btn-warning">Back to List</a>
                    </div>
                </div>
            </div>

            }

                
        </div>
    </div>
</section>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Units_Details/Index.cshtml
@{
    ViewBag.Title = "Index";
    
}

<section>
    <div class="card mt-2">
        <div class="card-body">
            <h5 class="card-title">Units</h5>

            <div class="formtabl">
                @Html.Action("IndexPartial", "Units_Details", new { area = "Inventory" })
            </div>
            <section class="btns d-none">
                <button class="btnSubmit btn btn-primary">Save</button>
                <button class="btnCancel btn btn-danger">Cancel</button>
                <label class="text-danger"></label>
            </section>
         

        </div>
    </div>
</section>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    var Id = 0;
    $(document).on('click', '.btnadd', function () {
        $.get('/Inventory/Units_Details/CreatePartial', function (response) {
            $('.btns').removeClass('d-none');
            $('.formtabl').empty();
            $('.formtabl').append(response);
        });
    });
    $(document).on('click', '.btnSubmit', function () {
        $('tbody').empty();
        var name = $('input[name="Name"]').val();
        $('label.text-danger').empty();
        if (name == "") {
            $('label.text-danger').append('Please Enter Unit');
            return false;
        }
       
        $.post('/Inventory/Units_Details/Add', { name, Id},
            function (data, status) {
                Swal.fire(
                    'Suceed!',
                    data,
                    'success'
                )
                LoadProjects();
                Id = 0;
                $('input[name="Name"]').val('');
                $('input[name="Description"]').val('');
            });

    });
    $(document).on('click', '.btnEdit', function () {
        debugger
        var id = $(this).attr('Id');
        Id = id;
        $.get('/Inventory/Units_Details/CreatePartial?id=' + id, function (response) {
            $('.btns').removeClass('d-none');
            $('.formtabl').empty();
            $('.formtabl').append(response);
        });
    })
    $(document).on('click', '.btnCancel', function () {
        $.get('/Inventory/Category_Details/IndexPartial', function (response) {
            $('.formtabl').empty();
            $('.formtabl').append(response);
            $('.btns').addClass('d-none');
            Id = 0;
        });
    })
    function LoadProjects() {
        $.get('/Inventory/Units_Details/IndexPartial', function (response) {
            $('.formtabl').empty();
            $('.formtabl').append(response);
            $('.btns').addClass('d-none');
            Id = 0;
        });
    }
    $(document).on('click', '.btndelete', function () {
        var id = $(this).attr('Id');
        Id = id;
        Swal.fire({
            title: 'Are you sure?',
            text: 'You will not be able to recover this Unit & related data will also!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.value) {
                $.get('/Inventory/Units_Details/Delete?id=' + id, function (response) {
                    LoadProjects();
                    Id = 0;
                })
            } else {
                Swal.fire(
                    'Cancelled',
                    'Unit is active :)',
                    'error'
                )
            }
        });
    });
</script>

AmeenTraning/AmeenTraning/Areas/Inventory/Views/Units_Details/IndexPartial.cshtml
@model IEnumerable<AmeenTraning.Models.Units_Details>

@{

    int SR = 0;
}
    <table class="table">
        <thead>
            <tr>
                <th>SR</th>
                <th>
                    Name
                </th>
                <th>
                    Added by
                </th>
                <th>
                    Modified by
                </th>
                <th>
                    Date Created
                </th>
                <th>
                    Date Modified
                </th>
                <th>
                    <div>
                        <button type="button" class="btn btn-primary btnadd">
                            Add
                        </button>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                SR++;
                <tr>
                    <td>@SR</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created_By)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Modified_By)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date_Created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date_Modified)
                    </td>
                    <td>

                        <button Id="@item.Unit_Id" class="btn btnEdit btn-warning">Edit</button>
                        <button Id="@item.Unit_Id" class="btn btndelete btn-danger">Delete</button>
                    </td>
                </tr>
            }
        </tbody>

    </table>